### ISSUE TITLE
InvalidParameterCombination: Cannot find version 12.7 for postgres

### ISSUE THREAD

**Issue by BradleyYeo** [hashicorp/learn-terraform-rds-upgrade#4]
│ Error: Error creating DB Instance: InvalidParameterCombination: Cannot find version 12.7 for postgres
│       status code: 400, request id: a33fdc8c-0b96-4e47-a166-38070dbf73fe
│ 
│   with aws_db_instance.education,
│   on main.tf line 75, in resource "aws_db_instance" "education":
│   75: resource "aws_db_instance" "education" {
│

**Comment by ritsok** [comment]
Thanks, merging a fix!
